# Generated by Django 4.2.6 on 2023-10-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_tags_article_scopes_rename_tag_name_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='tags',
        ),
    ]
